spring:
  profiles:
    active: INFO
---
spring:
  config:
    activate:
      on-profile: INFO
  application:
    name: easy-notes
  datasource:
    url: jdbc:mysql://localhost:3306/notes_app
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  file:
    path: loggingInfo
  level:
    root: INFO
